### ISSUE TITLE
use the OpenAI api to get a set of 5 questions (and answers) which is basically a quiz on all the finance related events that took place this week

### ISSUE THREAD

**Issue by lakimapturn** [FinSimIQ/fin-sim-server#11]
- Ensure to copy the env file from the google drive library
- Ask the model to give you a summary of 5 events that happened this week. 
- Ask chatgpt for a description about the event so that that can be given after the person answers.
- Refer online or look into the github page I put in the discord channel to see how previous members communicated with apis

**Comment by oskarbringle** [comment]
just made a pr, if you would like to check it out
