### ISSUE TITLE
Using OpenAI to generate course content

### ISSUE THREAD

**Issue by lakimapturn** [FinSimIQ/fin-sim-server#28]
here is the description of what the endpoint will e:xpect
- difficulty level
- topic
- description of the subtopics we want to focus on (there should be like 3 subtopics)
- It should call the create quiz api/function to make the quiz questions 

We decided to keep the subtopics limited to 3 just for simplicity for now. Maybe as we move forward we may change this.

**Comment by oskarbringle** [comment]
create a quiz get an id, then assign that id to course content object
